name: Shuttle Deploy Until Success

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Rust build and test"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy
        id: deploy
        uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}

  retry_deploy:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ needs.deploy.outputs.deploy == 'failure' }}
    steps:
      - name: Retry Deployment
        run: echo "Retrying deployment..."

      - name: Trigger Deployment
        uses: actions/github-script@v4
        with:
          script: |
            const { data: workflows } = await github.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const lastWorkflow = workflows.workflow_runs[0];

            if (lastWorkflow.conclusion === 'failure') {
              const response = await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_file: '.github/workflows/your-workflow-file.yml'
              });
              console.log(response);
            }
