name: Shuttle Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Rust build and test"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}